#!/usr/bin/env ruby

Jane.boot!

BEGIN {
  begin
    require('rubygems')
  rescue LoadError
    abort('You must have RubyGems installed to run Jane!')
  end

  bundler_loaded =
    begin
      require('bundler')
    rescue LoadError
      false
    end

  unless bundler_loaded
    bundler_version = ENV['JANE_BUNDLER_VERSION'] || '1.11.2'
    bundler_gem_path = File.expand_path("vendor/bundler-#{bundler_version}.gem")

    if File.exist?(bundler_gem_path)
      require 'rubygems/package'
      bundler_gem_package = Gem::Package.new(bundler_gem_path)
      bundler_gem_package.spec.activate
    end
  end

  abort('Unable to load Bundler!') unless defined?(Bundler)

  ENV['JANE_RB_LIB_DIR'] ||= File.expand_path('src/rb')
  ENV['BUNDLE_GEMFILE'] ||= File.expand_path('Gemfile')

  require 'bundler/setup'
  require 'jane'

  abort('Unable to boot Jane!') unless defined?(Jane)
}
